[FIX] account: prevent an errors when accessing reports without data
Currently error is generated when  try to edit 'Invoices' or
'Invoices without Payment' reports in studio mode when there is no record.

Steps to reproduce:

- Install an 'account' and 'web_studio' module (Without demo data).
- Navigate to invoicing / Customers / Invoices and open a web studio mode.
-  Open reports  and click on the 'Invoice' or 'Invoices without Payment'
reports.
- Click on 'EDIT SOURCES'.

TypeError: 'bool' object is not subscriptable

The issue occurs when the system tries to access a boolean value which is
stored in 'Tax_totals' in the 'document_tax_totals' template [1] and this
a boolean value is passed into 'tax_totals' from this line [2] because
record is not available.

link [1]: https://github.com/odoo/odoo/blob/a8daed02c58ab69cdea57a8f97065e229b07f0ab/addons/account/views/report_invoice.xml#L200-L201
link [2]: https://github.com/odoo/odoo/blob/a8daed02c58ab69cdea57a8f97065e229b07f0ab/addons/account/models/account_move.py#L1348

To resolve the issue, Add a condition that checks whether the 'Tax_totals' is
available before call the 'document_tax_totals' template.

sentry-4499699758