[FIX] payment_stripe: handle timeout error when connect with stripe
When the user connect with Stripe in the payment provider and an API request
takes longer than 60 seconds then a ReadTimeout error will occur.

Line 1: https://github.com/odoo/odoo/blob/29a40a30f3bf7a4a3a205e54fb84e569691d961f/addons/payment_stripe/models/payment_provider.py#L413-L418

Error: HTTPSConnectionPool(host='stripe.api.odoo.com', port=443): Read timed out
(read timeout=60)

To handle this situation, the code has been updated to ensure that if the system
takes more than 60 seconds to connect with Stripe then raises a logger warning.

sentry-4506249274