Cherry pick of a1458f3007d356680449c4036bc32515e6210d58 failed
stdout:
Auto-merging addons/l10n_es/data/template/account.tax-es_common.csv
CONFLICT (content): Merge conflict in addons/l10n_es/data/template/account.tax-es_common.csv

stderr:
15:33:56.701970 git.c:463               trace: built-in: git cherry-pick a1458f3007d356680449c4036bc32515e6210d58
error: could not apply a1458f3007d3... [IMP] l10n_es: add 5% non-deductible tax
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: