Cherry pick of 8540e8e9da070b1246538aa571e8221c65bea1bc failed
stdout:
Auto-merging addons/website_slides/i18n/website_slides.pot
Auto-merging addons/website_slides/static/src/js/tours/slides_tour.js
CONFLICT (content): Merge conflict in addons/website_slides/static/src/js/tours/slides_tour.js

stderr:
16:04:37.720384 git.c:463               trace: built-in: git cherry-pick 8540e8e9da070b1246538aa571e8221c65bea1bc
error: could not apply 8540e8e9da07... [FIX] website_slides: rectify the trigger on course title input field
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: